query getAllArticles($limit: Int) {
  articles(sort: "createdAt:desc", limit: $limit) {
    id
    title
    createdAt
    text
    tags {
      name
    }
    image {
      url
    }
  }
  tags {
    id
    name
  }
}
