query getAllExercises {
  exercises {
    id
    name
    alias
    description 
    category
    video
    products {
      id
      name
      price
      images {
        id
        url
      }
    }
  }
}