query {
  stronaGlowna {
    landing {
      id
      header
      subheader
      video
    }
    coaches {
      id
      name
      description
      image {
        url
      }
    }
    opinions {
      id
      name
      quote
      image {
        url
      }
    }
  }
}