query getSingleProgram($id: ID!) {
  program(id: $id) {
    id
    nazwa
    cena
    foto {
      url
    }
    lessons {
      id
      nazwa
      opis
      wideo
      foto {
        url
      } 
    }
  }
}