query getSingleProduct($id: ID!) {
  product(id: $id) {
    id
    name
    description 
    price
    available
    exercises {
      id
      name 
      alias
    }
    images {
      id
      url
    }
  }, 
  products(where: { id_ne: $id }) {
    id
    name
    description 
    price
    images {
      id
      url
    }
  }
}