query getSingleProgram($id: ID!) {
  program(id: $id) {
    id
    name
    price
    description
    image {
      id
      url
    }
    lessons {
      id
      name
      description
      video
    }
  }
}