query getSingleProgram($id: ID!) {
  program(id: $id) {
    id
    name
    price
    description
    image {
      url
    }
    lessons {
      id
      name
      description
      video
      image {
        url
      } 
    }
  }
}